services:

  client:
    build: 
     context: ./client 
    working_dir: /client
    environment:
      - SERVER_URL=http://server:4000/show
    volumes:
      - ./client/src:/client/src
      - ./client/.svelte-kit:/client/.svelte-kit
    ports:
      - 3000:3000
    depends_on:
      - server
    command: npm run dev

  server:
    build: 
     context: ./server
    working_dir: /server
    volumes:
      - ./server:/server
    environment:
      - LOG_LEVEL=debug
      - HTTP_PORT=4000
    ports: 
      - 4000:4000
    command: go run main.go

